#pragma once

enum ActionType {
	ACTION_NONE,
	ACTION_CLOSE_PARENT,
	ACTION_MOVE,
	ACTION_CUT,
	ACTION_DRAG,
	ACTION_DROP,
	ACTION_PICK_ITEM,
	ACTION_CRAFT_CAMPFIRE,
	ACTION_CRAFT_TREE,
	ACTION_PICK_BRANCH,
	ACTION_LAST
};